### ISSUE TITLE
Responsive layout large margins

### ISSUE THREAD

**Issue by lkraider** [RocketChat/Rocket.Chat.Docs#17]
When the element `content-html` reaches 692px width, the display of the `aside` tags add large margins making the main content compress:
![screen shot 2016-04-18 at 22 24 23](https://cloud.githubusercontent.com/assets/52256/14624834/7af20b90-05b4-11e6-8260-986304a4de7f.png)
![screen shot 2016-04-18 at 22 25 18](https://cloud.githubusercontent.com/assets/52256/14624836/7ef9af2c-05b4-11e6-8e50-65b36c32fbb8.png)

---

Compared to 691px width:
![screen shot 2016-04-18 at 22 26 10](https://cloud.githubusercontent.com/assets/52256/14624846/9ab4c7ec-05b4-11e6-9f0f-8cfb0f8bf33a.png)
![screen shot 2016-04-18 at 22 31 14](https://cloud.githubusercontent.com/assets/52256/14624947/4b7d5846-05b5-11e6-99d0-09ad938d74a8.png)

**Comment by gmsecrieru** [comment]
Thanks, @lkraider ! Would you submit this layout fix as a pull request?

**Comment by frdmn** [comment]
I think this is actually intended by the design of the documentation system. I am pretty certain that the "margin" you mentioned is actually just another view for showing documentation examples, a feature of Redoc that we don't use, thus they are empty. In the second state (`@media screen and (max-width: 991px)` media query), they move below each of the sections. But again, since we don't use the examples, it's empty and doesn't show up.

**Comment by Sing-Li** [comment]
@frdmn  brilliant!   So if we wait and wait, that big blank space will still never go away - it is not a bug.  Unless we change the redoc layout  :+1:

**Comment by gmsecrieru** [comment]
Closing as this is handled by the new layout
