### ISSUE TITLE
Broken links (once again)

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat.Docs#31]
There are some new issues regarding the links. Checkout the [Ubuntu guide](https://rocket.chat/docs/master/installing-and-updating/manual-instalation/ubuntu) for example:

- General articles, for example: "Creating the First Admin" links to `https://rocket.chat/5.%20Server%20Management%2FCreate%20the%20first%20admin.md`
- Hash anchors, for example: "step" links to `https://rocket.chat/docs/undefined#2-install-rocketchat`"

**Comment by rhyspowell** [comment]
another broken link [here](https://rocket.chat/docs/master/installing-and-updating/docker-containers/available-images/) 

I dont mind putting in fixes if some one can give me the heads up on how linking works as I have no idea how everything is being rendered for the web site. Is it just md as per normal wiki standard?

**Comment by frdmn** [comment]
@rhyspowell Thanks for the offer, but I think we rather need to fix the link generation in [redoc (the docu system)](https://github.com/RocketChat/redoc). We aim to keep working links in the original source / GitHub markdown viewer as well as the documentation system. That's why we need to "transform" them for redoc manually.

Let's wait for some input from the @RocketChat/documentation-and-wiki team :)

**Comment by rhyspowell** [comment]
Thats cool. Thought there might be some document building system. Will let them fix that and then check what I have found

**Comment by gmsecrieru** [comment]
@frdmn @rhyspowell 

We are working on this, but for this particular example (Ubuntu) the GitHub link is also incorrect -- possibly due to the new repository structure. 

It is worth mentioning that we still might find a few broken links in the long run because:
a) the changes regarding the permalinks were aded while there were already stale/outdated URLs in the documentation markdown files
b) as mentioned, we have changed the repository structure for a lot of directories, thus these changes might not have been applied throughout the whole documentation.

There is a new release of `RocketChat/redoc` coming soon, but it is possible that the issue with the relative, #hashed URLs still exist. I will work on it as soon as we have our new stable version.

Thanks a lot for the help on this!

**Comment by tholu** [comment]
Another broken link in Rocket.Chat admin: https://github.com/RocketChat/Rocket.Chat/wiki/LDAP-Authentication

Information seems to get lost in this restructuring process, I liked the Github wiki way better.

**Comment by engelgabriel** [comment]
Hi @tholu thanks for point out the link. This is a transition period and things will break, but after we finish this migration, we will end up with a easy to contribute documentation on Github that is 100% funcional and compatible with the Documentation generator.

**Comment by tholu** [comment]
@engelgabriel Looking forward to it 👍  Documentation seems to work again as well.

**Comment by engelgabriel** [comment]
all broken links have been mapped and fixed.
